logging:
  level:
    com:
      scnl:
        fintech:
          dhanwan:
            kycinfo: DEBUG
  file: Log/myLog.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] -%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%X{CORRELATION_ID}] [%thread] %-5level %logger{40}-%msg%n'
server:
  port: 8080
spring.profiles: dev

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/dhanwan?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 50
  jpa:
    show-sql: false
    properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: xyz@gmail.com
    password: XXXXXXXX
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        transport:
          protocol: smtp
  redis:
    database: 0
    host: ${REDIS_IP}
    port: ${REDIS_PORT}

  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
